# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "62cc2d5507cd470c3ef7b9cba71b729b"
name = "Next Connector"
application_url = "https://example.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_inventory,write_orders,read_orders,read_customers,read_fulfillments,write_products,read_locations"

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/orders/fulfilled"
  topics = [ "orders/fulfilled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/orders/partially_fulfilled"
  topics = [ "orders/partially_fulfilled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/orders/cancelled"
  topics = [ "orders/cancelled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/inventory/levels_update"
  topics = [ "inventory_levels/update" ]

[auth]
redirect_urls = ["https://example.com/auth/callback",
  "https://example.com/auth/callback"]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
